# Предложения по аренде
## Получить список предложений по аренде
GET http://localhost:5000/offers?limit=2 HTTP/1.1
Content-Type: application/json

###

## Получить детальную информацию по одному предложению по аренде
GET http://localhost:5000/offers/6492d52517d2e5a5496dfe22 HTTP/1.1

###

## Удалить предложение по аренде
DELETE http://localhost:5000/offers/6492d52517d2e5a5496dfe22 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IlZpdGFseUBtYWlsLnJ1IiwiaWQiOiI2NDkyZDQzNTE3ZDJlNWE1NDk2ZGZlMTgiLCJpYXQiOjE2ODczNDQyMTgsImV4cCI6MTY4NzUxNzAxOH0.Rwjez_RNPUL9PMBXjUTFP_MomLlxIJorCjDJLIb7M9M

###

## Добавить новое предложение по аренде
## Обязательно в cityId указать ID существующего в базе города!!!
POST http://localhost:5000/offers HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IlZpdGFseUBtYWlsLnJ1IiwiaWQiOiI2NDkyZDQzNTE3ZDJlNWE1NDk2ZGZlMTgiLCJpYXQiOjE2ODczNDQyMTgsImV4cCI6MTY4NzUxNzAxOH0.Rwjez_RNPUL9PMBXjUTFP_MomLlxIJorCjDJLIb7M9M

{
  "title": "Test New Offer",
  "description": "The minimum test description",
  "cityId": "6492d0ad4ab772e816b13f22",
  "isPremium": true,
  "type": "house",
  "bedrooms": 8,
  "maxGuests": 10,
  "price": 190,
  "goods": ["Laptop friendly workspace"],
  "location": { "latitude": 42.3, "longitude": 2 }
}

###

## Редактировать предложение по аренде
PATCH http://localhost:5000/offers/6492d52517d2e5a5496dfe22 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IlZpdGFseUBtYWlsLnJ1IiwiaWQiOiI2NDkyZDQzNTE3ZDJlNWE1NDk2ZGZlMTgiLCJpYXQiOjE2ODczNDQyMTgsImV4cCI6MTY4NzUxNzAxOH0.Rwjez_RNPUL9PMBXjUTFP_MomLlxIJorCjDJLIb7M9M

{
  "price": 427
}

###

## Список комментариев к объявлению
GET http://localhost:5000/offers/6492d52517d2e5a5496dfe22/comments HTTP/1.1
Content-Type: application/json

###

## Отправка одной фотографии предложениея по аренде

POST http://localhost:5000/offers/6492d52517d2e5a5496dfe22/image HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IlZpdGFseUBtYWlsLnJ1IiwiaWQiOiI2NDkyZDQzNTE3ZDJlNWE1NDk2ZGZlMTgiLCJpYXQiOjE2ODczNDQyMTgsImV4cCI6MTY4NzUxNzAxOH0.Rwjez_RNPUL9PMBXjUTFP_MomLlxIJorCjDJLIb7M9M

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="previewImage"; filename="123.png"
Content-Type: image/png

< ../../../static/1.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

## Отправка колекции фотографий предложениея по аренде

POST http://localhost:5000/offers/6492d52517d2e5a5496dfe22/pictures HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IlZpdGFseUBtYWlsLnJ1IiwiaWQiOiI2NDkyZDQzNTE3ZDJlNWE1NDk2ZGZlMTgiLCJpYXQiOjE2ODczNDQyMTgsImV4cCI6MTY4NzUxNzAxOH0.Rwjez_RNPUL9PMBXjUTFP_MomLlxIJorCjDJLIb7M9M

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="123.png"
Content-Type: image/png

< ../../../static/1.jpg

------WebKitFormBoundary7MA4YWxkTrZu0gW--

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="123.png"
Content-Type: image/png

< ../../../static/2.jpg

------WebKitFormBoundary7MA4YWxkTrZu0gW--

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="123.png"
Content-Type: image/png

< ../../../static/3.jpg

------WebKitFormBoundary7MA4YWxkTrZu0gW--

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="123.png"
Content-Type: image/png

< ../../../static/4.jpg

------WebKitFormBoundary7MA4YWxkTrZu0gW--

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="123.png"
Content-Type: image/png

< ../../../static/5.jpg

------WebKitFormBoundary7MA4YWxkTrZu0gW--

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="123.png"
Content-Type: image/png

< ../../../static/6.jpg

------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
