# Предложения по аренде
## Получить список предложений по аренде
GET http://localhost:5000/offers?limit=2 HTTP/1.1
Content-Type: application/json

###

## Получить детальную информацию по одному предложению по аренде
GET http://localhost:5000/offers/648d4a8456180852b32c6126 HTTP/1.1

###

## Удалить предложение по аренде
DELETE http://localhost:5000/offers/647f3cc538c28b7743c33d62 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IlZpdGFseUBtYWlsLnJ1IiwiaWQiOiI2NDdmMjg3MjlkYzJhMWEzNjRkOWY1MTQiLCJpYXQiOjE2ODYwNjQ3NzUsImV4cCI6MTY4NjIzNzU3NX0.KNJfBpAI-kSwFwrAAv_oOejVQUd28BVAMZMMKcMyV20

###

## Добавить новое предложение по аренде
## Обязательно в cityId указать ID существующего в базе города!!!
POST http://localhost:5000/offers HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IlZpdGFseUBtYWlsLnJ1IiwiaWQiOiI2NDhkNDliOTU2MTgwODUyYjMyYzYxMjAiLCJpYXQiOjE2ODY5ODEwNjgsImV4cCI6MTY4NzE1Mzg2OH0.sxent0XizSGMOjKs_DpESXDHfLK3C7P4rjWdOGBlbNs

{
  "title": "Test New Offer",
  "description": "The minimum test description",
  "cityId": "648d48efe614c50fa64ef8c9",
  "isPremium": true,
  "type": "house",
  "bedrooms": 8,
  "maxGuests": 10,
  "price": 190,
  "goods": ["Laptop friendly workspace"],
  "location": { "latitude": 42.3, "longitude": 2 }
}

###

## Редактировать предложение по аренде
PATCH http://localhost:5000/offers/647f360d951ea96d2c2fe391 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IlZpdGFseUBtYWlsLnJ1IiwiaWQiOiI2NDdmMjg3MjlkYzJhMWEzNjRkOWY1MTQiLCJpYXQiOjE2ODYwNjQ3NzUsImV4cCI6MTY4NjIzNzU3NX0.KNJfBpAI-kSwFwrAAv_oOejVQUd28BVAMZMMKcMyV20

{
  "price": 427
}

###

## Список комментариев к объявлению
GET http://localhost:5000/offers/647f3cc538c28b7743c33d62/comments HTTP/1.1
Content-Type: application/json

###

## Отправка одной фотографии предложениея по аренде

POST http://localhost:5000/offers/647f360d951ea96d2c2fe391/image HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IlZpdGFseUBtYWlsLnJ1IiwiaWQiOiI2NDdmMjg3MjlkYzJhMWEzNjRkOWY1MTQiLCJpYXQiOjE2ODY3Mzc3MzcsImV4cCI6MTY4NjkxMDUzN30.0unNZjwSTorJkPj3fXyRhq9s92dyWt1inLLD25gdk3w

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="previewImage"; filename="123.png"
Content-Type: image/png

< ../../../static/1.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

## Отправка колекции фотографий предложениея по аренде

POST http://localhost:5000/offers/647f360d951ea96d2c2fe391/pictures HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IlZpdGFseUBtYWlsLnJ1IiwiaWQiOiI2NDdmMjg3MjlkYzJhMWEzNjRkOWY1MTQiLCJpYXQiOjE2ODY3Mzc3MzcsImV4cCI6MTY4NjkxMDUzN30.0unNZjwSTorJkPj3fXyRhq9s92dyWt1inLLD25gdk3w

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="123.png"
Content-Type: image/png

< ../../../static/1.jpg

------WebKitFormBoundary7MA4YWxkTrZu0gW--

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="123.png"
Content-Type: image/png

< ../../../static/2.jpg

------WebKitFormBoundary7MA4YWxkTrZu0gW--

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="123.png"
Content-Type: image/png

< ../../../static/3.jpg

------WebKitFormBoundary7MA4YWxkTrZu0gW--

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="123.png"
Content-Type: image/png

< ../../../static/4.jpg

------WebKitFormBoundary7MA4YWxkTrZu0gW--

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="123.png"
Content-Type: image/png

< ../../../static/5.jpg

------WebKitFormBoundary7MA4YWxkTrZu0gW--

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="123.png"
Content-Type: image/png

< ../../../static/6.jpg

------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
