## Создать комментарий
POST http://localhost:5000/comments HTTP/1.1
Content-Type: application/json

{
  "text": "Life is like riding a bicycle. To keep your balance, you must keep moving.",
  "rating": 4,
  "offerId": "647745f79cbf78edb8c64ac7",
  "userId": "647745f69cbf78edb8c64aac"
}

###
