# Города
## Получить список городов
GET http://localhost:5000/cites HTTP/1.1
Content-Type: application/json

###

## Получить детальную информацию по одному городу
GET http://localhost:5000/cites/647745f69cbf78edb8c64aaa HTTP/1.1
Content-Type: application/json

###

## Получить список предложений по аренде по одному городу
GET http://localhost:5000/cites/647745f69cbf78edb8c64aaa/offers HTTP/1.1
Content-Type: application/json

###
