# Пользователи
## Создать нового пользователя

POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "Vitaly",
  "email": "Vitaly@mail.ru",
  "avatarPath": "torrance.png",
  "password": "12345678",
  "isPro": true
}

###

## Авторизовать пользователя

POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "Vitaly@mail.ru",
  "password": "12345678"
}

###

## Отправка аватарки пользователю

POST http://localhost:5000/users/647f28729dc2a1a364d9f514/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IlZpdGFseUBtYWlsLnJ1IiwiaWQiOiI2NDdmMjg3MjlkYzJhMWEzNjRkOWY1MTQiLCJpYXQiOjE2ODYwNTY2ODQsImV4cCI6MTY4NjIyOTQ4NH0.JlIHegpfDJTu2k7NgqR_DTorviXMREvtIAaCdmH3vJo

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatarPath"; filename="123.png"
Content-Type: image/png

< /Users/19395113/Desktop/123.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

## Проверить токен пользователя
GET http://localhost:5000/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IlZpdGFseUBtYWlsLnJ1IiwiaWQiOiI2NDdmMjg3MjlkYzJhMWEzNjRkOWY1MTQiLCJpYXQiOjE2ODYwNTY2ODQsImV4cCI6MTY4NjIyOTQ4NH0.JlIHegpfDJTu2k7NgqR_DTorviXMREvtIAaCdmH3vJo

###
