# Пользователи
## Создать нового пользователя

POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "Vitaly",
  "email": "Vitaly@mail.ru",
  "password": "12345678",
  "isPro": true
}

###

## Авторизовать пользователя

POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "Vitaly@mail.ru",
  "password": "12345678"
}

###

## Отправка аватарки пользователю

POST http://localhost:5000/users/648d49b956180852b32c6120/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IlZpdGFseUBtYWlsLnJ1IiwiaWQiOiI2NDhkNDliOTU2MTgwODUyYjMyYzYxMjAiLCJpYXQiOjE2ODY5ODEwNjgsImV4cCI6MTY4NzE1Mzg2OH0.sxent0XizSGMOjKs_DpESXDHfLK3C7P4rjWdOGBlbNs

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatarPath"; filename="123.png"
Content-Type: image/png

< ../../../static/default-avatar.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

## Проверить токен пользователя
GET http://localhost:5000/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IlZpdGFseUBtYWlsLnJ1IiwiaWQiOiI2NDdmMjg3MjlkYzJhMWEzNjRkOWY1MTQiLCJpYXQiOjE2ODY3Mzc3MzcsImV4cCI6MTY4NjkxMDUzN30.0unNZjwSTorJkPj3fXyRhq9s92dyWt1inLLD25gdk3w

###
